cc_library(
    name = "break_the_pieces",
    srcs = ["src/main.cpp"],
    hdrs = ["src/main.h"],
)

cc_test(
    name = "main_test",
    srcs = ["test/test.cpp"],
    deps = ["@com_google_googletest//:gtest_main"],
)